//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitchBot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("b35io4wr1yt2k6n9frnfllkraeymo5")]
        public string clientid {
            get {
                return ((string)(this["clientid"]));
            }
            set {
                this["clientid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9xxjmh1pbnl0vzvwdsx8seh8ja8huc")]
        public string clientsecret {
            get {
                return ((string)(this["clientsecret"]));
            }
            set {
                this["clientsecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CH6huP8qYlSvHeOhvB9vcQ==bCNTg08FarvFkV9I")]
        public string APINinjaKey {
            get {
                return ((string)(this["APINinjaKey"]));
            }
            set {
                this["APINinjaKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B8HxqfVm10b9oc6a")]
        public string OBSWebSocketAuth {
            get {
                return ((string)(this["OBSWebSocketAuth"]));
            }
            set {
                this["OBSWebSocketAuth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fb9e634a97ce4f37a9cbdcf4c10f6765")]
        public string SpotifyClientId {
            get {
                return ((string)(this["SpotifyClientId"]));
            }
            set {
                this["SpotifyClientId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cf94d6d575294654825ec6f17944976b")]
        public string SpotifyClientSecret {
            get {
                return ((string)(this["SpotifyClientSecret"]));
            }
            set {
                this["SpotifyClientSecret"] = value;
            }
        }
    }
}
